config/routes.rb
Rails.application.routes.draw do
  resources :cfcposts
  devise_for :cfcusers
  resources :cfccomments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post "new_cfcuser_cfcreaction", to: "cfcreactions#new_cfcuser_cfcreaction", as: "new_cfcuser_cfcreaction"
  # Defines the root path route ("/")
  # root "articles#index"
  root "cfcposts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cfccomment.rb
class Cfccomment < ApplicationRecord
  belongs_to :cfcuser, optional: true
  belongs_to :cfcpost
end

app/models/cfcpost.rb
class Cfcpost < ApplicationRecord
  belongs_to :cfcuser
  has_many :cfcreactions, dependent: :destroy
  has_many :cfcusers, through: :cfcreactions
  has_many :cfccomments, dependent: :destroy
  
  
  
end

app/models/cfcreaction.rb
class Cfcreaction < ApplicationRecord
  belongs_to :cfcuser
  belongs_to :cfcpost, optional: true


  validates :kind, acceptance: {
    accept: %w[like dislike ]
    }
    def self.kinds
      %w[ like dislike ]
      end
     

end

app/models/cfcuser.rb
class Cfcuser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :cfcposts, through: :cfcreactions
         has_many :cfcreactions
         has_many :cfccomments
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :nickname])
    end
end

app/controllers/cfccomments_controller.rb
class CfccommentsController < ApplicationController
    before_action :set_cfccomment, only: %i[ show destroy ] 
    before_action :redirect_si_user_no_coincide_con_creador_del_comment , only: %i[ edit update destroy ]
  
    # GET /comments/1 or /comments/1.json
    def show
    end
  
    # GET /cfccomments/new
    def new
      @cfccomment = Cfccomment.new
    end
  
    # GET /cfccomments/1/edit
    def edit
    end
  
    # POST /cfccomments or /cfccomments.json
    def create
      @cfccomment = Cfccomment.new(cfccomment_params)
      if cfcuser_signed_in?
      @cfccomment.cfcuser = current_cfcuser
      end
      respond_to do |format|
        if @cfccomment.save
          format.html { redirect_to cfccomments_url(@cfccomment), notice: "Tú comentario fue creado con éxito." }
        else
          format.html { redirect_to cfccomments_url(@cfccomment), notice: "No se pudo crear tú comentario" }
        end
      end
    end
  
    # DELETE /comments/1 or /comments/1.json
    def destroy
      @cfccomment.destroy
      respond_to do |format|
        format.html { redirect_to cfccomments_url(@cfccomment), notice: "Tú comentario fue eliminado con éxito" }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_cfccomment
        @cfccomment = Cfccomment.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def cfccomment_params
        params.require(:cfccomment).permit(:content, :cfcuser_id, :cfcpost_id )
      end
  
      def redirect_si_user_no_coincide_con_creador_del_comment
          if current_cfcuser.id!= @cfccomment.cfcuser_id
            redirect_to root_path, notice: "No puedes realizar esta acción"
        end
      end
end

app/controllers/cfcposts_controller.rb
class CfcpostsController < ApplicationController
  before_action :set_cfcpost, only: %i[ show edit update destroy ]
  before_action :authenticate_cfcuser!, except: %i[ index show ]
  before_action :redirect_si_user_no_coincide_con_creador_del_post , only: %i[ edit update destroy ]

  # GET /cfcposts or /cfcposts.json
  def index
    @cfcposts = Cfcpost.all
  end

  # GET /cfcposts/1 or /cfcposts/1.json
  def show
    @cfccomment = Cfccomment.new
    @cfccomment = @cfcpost.cfccomments
  end

  # GET /cfcposts/new
  def new
    @cfcpost = Cfcpost.new
  end

  # GET /cfcposts/1/edit
  def edit
  end

  # POST /cfcposts or /cfcposts.json
  def create
    @cfcpost = Cfcpost.new(cfcpost_params)
    @cfcpost.cfcuser = current_cfcuser
    respond_to do |format|
      if @cfcpost.save
        format.html { redirect_to cfcpost_url(@cfcpost), notice: "Cfcpost was successfully created." }
        format.json { render :show, status: :created, location: @cfcpost }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cfcpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cfcposts/1 or /cfcposts/1.json
  def update
    respond_to do |format|
      if @cfcpost.update(cfcpost_params)
        format.html { redirect_to cfcpost_url(@cfcpost), notice: "Cfcpost was successfully updated." }
        format.json { render :show, status: :ok, location: @cfcpost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cfcpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cfcposts/1 or /cfcposts/1.json
  def destroy
    @cfcpost.destroy

    respond_to do |format|
      format.html { redirect_to cfcposts_url, notice: "Cfcpost was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cfcpost
      @cfcpost = Cfcpost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cfcpost_params
      params.require(:cfcpost).permit(:image, :description, :cfcuser_id)
    end

    def redirect_si_user_no_coincide_con_creador_del_post
      if current_cfcuser.id != @cfcpost.cfcuser_id
          redirect_to root_path, notice: "No puedes realizar esta acción"
      end
    end

end

app/controllers/cfcreactions_controller.rb
class CfcreactionsController < ApplicationController
    before_action :authenticate_cfcuser!

    def new_cfcuser_cfcreaction
        @cfcuser = current_cfcuser
        @cfcpost = Cfcpost.find(params[:cfcpost_id])
        cfcreaction = Cfcreaction.find_by(cfcuser_id: @cfcuser.id, cfcpost_id: @cfcpost.id)
        if cfcreaction
        return flash.now[:alert] = 'Ya reaccionaste a esta publicación!'
        else
        @new_cfcreaction = Cfcreaction.new(cfcuser_id: @cfcuser.id, cfcpost_id: @cfcpost.id, kind: params[:kind])
        respond_to do |format|
        if @new_cfcreaction.save!
        format.html { redirect_to cfcpost_url(@cfcpost), notice: "Reaccionaste con éxito!" }
        else
        format.html { redirect_to cfcpost_url(@cfcpost), status: :unprocessable_entity }
        end
        end
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cfccomments_helper.rb
module CfccommentsHelper
end

app/helpers/cfcposts_helper.rb
module CfcpostsHelper
end

app/helpers/cfcreactions_helper.rb
module CfcreactionsHelper
end

app/views/cfccomments/_cfccomments.html.erb
<div class="card comments mt-3 mb-2">
  <div class="card-header border-bottom-0 font-weight-bold bg-transparent">Comentarios</div>
  <ul class="list-group list-group-flush">
    <% @cfcpost.cfccomments.each do |comment| %>
      <li class="list-group-item">
        <header class="comment-header"><strong><i class="fa-solid fa-cat fa-xl" style="color: #930606;">
        </i><%= (comment.cfcuser.nickname if comment.cfcuser) || "Anonymous" %></strong> wrote <%= distance_of_time_in_words(Time.current, comment.created_at) %> ago</header>
        <div class="comment-body"><strong><%= comment.content %></strong></div>
        <%= button_to "Eliminar comentario", comment, method: :delete %>
      </li>
    <% end %>

    <% if @cfcpost.cfccomments.empty? %>
      <li class="list-group-item text-center">Aún no hay comentarios para este post :(</li>
    <% end %>
  </ul>
</div>

  <div class="card bg-light new-comment">
    <div class="card-body">
      <p><strong>Deja tu comentario:</strong></p>
      
      <%= form_for @cfcpost.cfccomments.build do |f| %>
        <%= f.hidden_field :cfcpost_id, value: @cfcpost.id %>
<div>
    <%= f.label :content, style: "display: block" %>
    <%= f.text_field :content, class:"form-control" %>
  </div>

        <div class="text-right">
          <%= f.submit "Comentar", class: "btn btn-primary mt-2" %>
        </div>
        <div>
        <% end %>
  </div>

app/views/cfcposts/_cfcpost.html.erb
<div id="<%= dom_id cfcpost %>">

<div class="bg-light p-2 text-dark bg-opacity-75">
    <div class="text-center ">
  <p>
 <%= image_tag cfcpost.image, class:"photo" %>
  </p>


  <p>
    <strong><i class="fa-sharp fa-solid fa-shield-cat fa-2xl"></i> <%= cfcpost.cfcuser.nickname %> :</strong>
    <%= cfcpost.description %>
  </p>

  </div>
    </div>
</div>

app/views/cfcposts/_form.html.erb
<%= form_with(model: cfcpost) do |form| %>
  <% if cfcpost.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cfcpost.errors.count, "error") %> prohibited this cfcpost from being saved:</h2>

      <ul>
        <% cfcpost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <%# <div>
    <%= form.label :cfcuser_id, style: "display: block" %>
    <%# <%= form.text_field :cfcuser_id %>
  <%# </div> %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cfcposts/edit.html.erb
<div class="bg-light p-2 text-dark bg-opacity-75" >
<h1>Editando Publicación</h1>

<%= render "form", cfcpost: @cfcpost %>

<br>

<div>
  <%= link_to "Mostrar esta publicación", @cfcpost, class:"btn btn-dark" %> |
  <%= link_to "Volver a Publicaciones", cfcposts_path, class:"btn btn-dark" %>
</div>
</div>

app/views/cfcposts/index.html.erb
<p style="color: green"><%= notice %></p>

<div class=" mb-2 ">
<%= link_to "Crea una nueva publicación  ᵐᵉᵒʷˎˊ˗", new_cfcpost_path, class: "btn btn-success" %>
</div>

<div id="cfcposts">
  <% @cfcposts.each do |cfcpost| %>
    <%= render cfcpost %>
    <p class="mt-1">
      <%= link_to "Mostrar esta Publicación", cfcpost, class: "btn btn-dark" %>
    </p>
  <% end %>
</div>

app/views/cfcposts/new.html.erb
<div class="bg-light p-2 text-dark bg-opacity-75">
<h1>Nueva Publicación</h1>

<%= render "form", cfcpost: @cfcpost %>

<br>

<div>
  <%= link_to "Volver a Publicaciones", cfcposts_path, class: "btn btn-dark" %>
</div>
</div>

app/views/cfcposts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cfcpost %>
<div class="m-2">
<%= link_to "Volver a Publicaciones", cfcposts_path, class:"btn btn-dark"%>
</div>

<div class="bg-light m-1 p-1 text-dark bg-opacity-75">

 <%= render 'cfcreactions/options' %>


</div>

<% if @cfcpost.cfcuser == current_cfcuser  %> 
<div class="dropdown mt-3">
  <a class="btn btn-danger dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Opciones
  </a>
  <ul class="dropdown-menu">
      <li><%= button_to "Eliminar esta publicación", @cfcpost, method: :delete %></li>
    <li><%= link_to "Editar esta publicación", edit_cfcpost_path(@cfcpost), class:"dropdown-item"%></li>
  </ul>
</div>
 <% end %> 
<div>
<%= render 'cfccomments/cfccomments' %>
</div>

app/views/cfcreactions/_options.html.erb
<div class="container p-3">
<i class="fa-regular fa-thumbs-up fa-xl"></i>
<% Cfcreaction.kinds.each do |kind| %>
  <%= @cfcpost.cfcreactions.where(kind: kind).count %> 
 <% end %>
 <i class="fa-regular fa-thumbs-down fa-xl"></i>
<div class="d-flex justify-content-center">

 <% Cfcreaction.kinds.each do |kind| %>
 <%= button_to "#{kind.capitalize}", new_cfcuser_cfcreaction_path(cfcpost_id: @cfcpost.id, kind: kind), class:"btn btn-danger", method: :post %> 
 <% end %>
 
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crazyforcats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
<nav class="navbar navbar-expand-lg bg-dark" >
  <div class="container ">
<i class="fa-solid fa-cat fa-2xl" style="color: #ffffff;"></i>
    <%= link_to "Inicio", root_path, class:"navbar-brand tcolor" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarNavDropdown">
    <ul class="navbar-nav me-auto">
    </ul>
      <ul class="navbar-nav ms-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle tcolor" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if cfcuser_signed_in? %>
            <% if current_cfcuser.name %>
            Hola <%= current_cfcuser.name %>  
            <% else %>
            Hola <%= current_cfcuser.email %>
            <% end %>
            <% else %>
            Inicia sesión / Registrate
            <% end %>
          </a>
          <ul class="dropdown-menu">
          <% if cfcuser_signed_in? %>
            <li><%= button_to "Cerrar Sesión", destroy_cfcuser_session_path, class:"dropdown-item", method: :delete %></li>
            <% else %> 
            <li><%= link_to "Iniciar Sesión", new_cfcuser_session_path, class:"dropdown-item" %></li>
            <li><%= link_to "Registrarme", new_cfcuser_registration_path, class:"dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
<%# Creditos por imagen de fondo "https://www.freepik.es/vector-gratis/plantilla-fondo-estampado-amante-gatos_15080927.htm">Imagen de rawpixel.com en Freepik< %>

 
  <p class="notice"><%= notice %></p>
      <h1 class="tutilo"><u>~Crazy For Cats~</u></h1>
    <div class="row justify-content-center">

     <div class="col-6 text-center">
     
    <%= yield %>
</div>
</div>
    <script src="https://kit.fontawesome.com/8bcc232b0f.js" crossorigin="anonymous"></script>
  </body>
</html>